/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVseRouteImport } from './routes/api/vse'
import { Route as ApiTrendsSyncRouteImport } from './routes/api/trends-sync'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatTrendsRouteImport } from './routes/_authenticated/chat.trends'
import { Route as AuthenticatedChatPresetsRouteImport } from './routes/_authenticated/chat.presets'
import { Route as AuthenticatedChatNewRouteImport } from './routes/_authenticated/chat.new'
import { Route as AuthenticatedChatLibraryRouteImport } from './routes/_authenticated/chat.library'
import { Route as AuthenticatedChatDashboardRouteImport } from './routes/_authenticated/chat.dashboard'
import { Route as AuthenticatedChatCreditsRouteImport } from './routes/_authenticated/chat.credits'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVseRoute = ApiVseRouteImport.update({
  id: '/api/vse',
  path: '/api/vse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrendsSyncRoute = ApiTrendsSyncRouteImport.update({
  id: '/api/trends-sync',
  path: '/api/trends-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedChatTrendsRoute = AuthenticatedChatTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedChatPresetsRoute =
  AuthenticatedChatPresetsRouteImport.update({
    id: '/presets',
    path: '/presets',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedChatNewRoute = AuthenticatedChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedChatLibraryRoute =
  AuthenticatedChatLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedChatDashboardRoute =
  AuthenticatedChatDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedChatCreditsRoute =
  AuthenticatedChatCreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/chat.$threadId.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/trends-sync': typeof ApiTrendsSyncRoute
  '/api/vse': typeof ApiVseRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat/credits': typeof AuthenticatedChatCreditsRoute
  '/chat/dashboard': typeof AuthenticatedChatDashboardRoute
  '/chat/library': typeof AuthenticatedChatLibraryRoute
  '/chat/new': typeof AuthenticatedChatNewRoute
  '/chat/presets': typeof AuthenticatedChatPresetsRoute
  '/chat/trends': typeof AuthenticatedChatTrendsRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/trends-sync': typeof ApiTrendsSyncRoute
  '/api/vse': typeof ApiVseRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat/credits': typeof AuthenticatedChatCreditsRoute
  '/chat/dashboard': typeof AuthenticatedChatDashboardRoute
  '/chat/library': typeof AuthenticatedChatLibraryRoute
  '/chat/new': typeof AuthenticatedChatNewRoute
  '/chat/presets': typeof AuthenticatedChatPresetsRoute
  '/chat/trends': typeof AuthenticatedChatTrendsRoute
  '/chat': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/trends-sync': typeof ApiTrendsSyncRoute
  '/api/vse': typeof ApiVseRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/chat/credits': typeof AuthenticatedChatCreditsRoute
  '/_authenticated/chat/dashboard': typeof AuthenticatedChatDashboardRoute
  '/_authenticated/chat/library': typeof AuthenticatedChatLibraryRoute
  '/_authenticated/chat/new': typeof AuthenticatedChatNewRoute
  '/_authenticated/chat/presets': typeof AuthenticatedChatPresetsRoute
  '/_authenticated/chat/trends': typeof AuthenticatedChatTrendsRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/chat'
    | '/api/chat'
    | '/api/trends-sync'
    | '/api/vse'
    | '/chat/$threadId'
    | '/chat/credits'
    | '/chat/dashboard'
    | '/chat/library'
    | '/chat/new'
    | '/chat/presets'
    | '/chat/trends'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/chat'
    | '/api/trends-sync'
    | '/api/vse'
    | '/chat/$threadId'
    | '/chat/credits'
    | '/chat/dashboard'
    | '/chat/library'
    | '/chat/new'
    | '/chat/presets'
    | '/chat/trends'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/chat'
    | '/api/chat'
    | '/api/trends-sync'
    | '/api/vse'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/chat/credits'
    | '/_authenticated/chat/dashboard'
    | '/_authenticated/chat/library'
    | '/_authenticated/chat/new'
    | '/_authenticated/chat/presets'
    | '/_authenticated/chat/trends'
    | '/_authenticated/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTrendsSyncRoute: typeof ApiTrendsSyncRoute
  ApiVseRoute: typeof ApiVseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vse': {
      id: '/api/vse'
      path: '/api/vse'
      fullPath: '/api/vse'
      preLoaderRoute: typeof ApiVseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trends-sync': {
      id: '/api/trends-sync'
      path: '/api/trends-sync'
      fullPath: '/api/trends-sync'
      preLoaderRoute: typeof ApiTrendsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/trends': {
      id: '/_authenticated/chat/trends'
      path: '/trends'
      fullPath: '/chat/trends'
      preLoaderRoute: typeof AuthenticatedChatTrendsRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/presets': {
      id: '/_authenticated/chat/presets'
      path: '/presets'
      fullPath: '/chat/presets'
      preLoaderRoute: typeof AuthenticatedChatPresetsRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/new': {
      id: '/_authenticated/chat/new'
      path: '/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof AuthenticatedChatNewRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/library': {
      id: '/_authenticated/chat/library'
      path: '/library'
      fullPath: '/chat/library'
      preLoaderRoute: typeof AuthenticatedChatLibraryRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/dashboard': {
      id: '/_authenticated/chat/dashboard'
      path: '/dashboard'
      fullPath: '/chat/dashboard'
      preLoaderRoute: typeof AuthenticatedChatDashboardRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/credits': {
      id: '/_authenticated/chat/credits'
      path: '/credits'
      fullPath: '/chat/credits'
      preLoaderRoute: typeof AuthenticatedChatCreditsRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatCreditsRoute: typeof AuthenticatedChatCreditsRoute
  AuthenticatedChatDashboardRoute: typeof AuthenticatedChatDashboardRoute
  AuthenticatedChatLibraryRoute: typeof AuthenticatedChatLibraryRoute
  AuthenticatedChatNewRoute: typeof AuthenticatedChatNewRoute
  AuthenticatedChatPresetsRoute: typeof AuthenticatedChatPresetsRoute
  AuthenticatedChatTrendsRoute: typeof AuthenticatedChatTrendsRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatCreditsRoute: AuthenticatedChatCreditsRoute,
  AuthenticatedChatDashboardRoute: AuthenticatedChatDashboardRoute,
  AuthenticatedChatLibraryRoute: AuthenticatedChatLibraryRoute,
  AuthenticatedChatNewRoute: AuthenticatedChatNewRoute,
  AuthenticatedChatPresetsRoute: AuthenticatedChatPresetsRoute,
  AuthenticatedChatTrendsRoute: AuthenticatedChatTrendsRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTrendsSyncRoute: ApiTrendsSyncRoute,
  ApiVseRoute: ApiVseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
